#!/bin/bash
# 用 aptly 生成 APT 仓库：
#   incoming/*.deb  → aptly repo → snapshot → 发布到 conf/distros.txt 里的每个发行版
# 产物输出到 .aptly/public/（即将来 gh-pages 分支的内容）
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"

# --- 生成 aptly 配置（rootDir 指向仓库内 .aptly，随机器移动也不怕） ---
sed "s|__ROOT__|$ROOT|g" conf/aptly.conf.tpl > aptly.conf
CFG="$ROOT/aptly.conf"
APTLY="${APTLY:-aptly}"
command -v "$APTLY" >/dev/null || { echo "❌ 未找到 aptly，请安装或设置 APTLY 环境变量"; exit 1; }
# 注意：aptly 1.5 不认 APTLY_CONFIG 环境变量，统一用 -config 参数
apt() { "$APTLY" -config="$CFG" "$@"; }

# --- 确保签名密钥（KEYID 从 init-gpg.sh 输出解析） ---
KEYID="$(bash scripts/init-gpg.sh | sed -n 's/^KEYID=//p' | tail -1)"

# --- 检查待入库包 ---
shopt -s nullglob
DEBS_ALL=("$ROOT"/incoming/*.deb)
if [[ ${#DEBS_ALL[@]} -eq 0 ]]; then
    echo "❌ incoming/ 下没有 .deb"
    echo "   放入 .deb 后重试，或用 debs.list + CI 自动拉取"
    exit 1
fi

# --- 把超过 100 MB 的大包上传到 Cloudflare R2 ---
# 这些包会被 publish.sh 正常入库，但随后 rewrite-packages.sh 会把它们的
# Filename: 改指向 R2 公网 URL，避开 GitHub Pages 100 MB 单文件限制。
# R2 凭据在 CI 里通过 secrets 注入；本地运行时从 ~/.codex/.env 加载。
bash scripts/upload-to-r2.sh

# --- 按包名+架构去重：同一包名同一架构只保留版本最高的 .deb ---
# incoming/ 是 git 持久化目录，历史文件会残留；全量加入会让旧版本反复入库。
# 注意键必须是 包名+架构：同包名的 amd64 与 arm64 是两个不同的包，不能互相淘汰。
# 大于 R2_THRESHOLD_BYTES（默认 100 MB）的包不进入 aptly 仓库，
# 它们的信息会通过 rewrite-packages.sh 独立追加到 Packages 文件。
R2_THRESHOLD_BYTES="${R2_THRESHOLD_BYTES:-104857600}"
declare -A BEST=() BEST_VER=() SEEN_NAMES=()
# R2_DEBS: key=包名/架构, value=本地 .deb 路径（被 rewrite 阶段读取使用）
declare -A R2_DEBS=()
for d in "${DEBS_ALL[@]}"; do
    pname="$(dpkg-deb -f "$d" Package)"
    pver="$(dpkg-deb -f "$d" Version)"
    parch="$(dpkg-deb -f "$d" Architecture)"
    if [[ -z "$pname" ]]; then echo "⚠️  跳过无法解析的包: $d"; continue; fi
    size=$(stat -c%s "$d")
    key="${pname}/${parch}"
    if [[ $size -gt $R2_THRESHOLD_BYTES ]]; then
        R2_DEBS[$key]="$d"
        continue
    fi
    if [[ -z "${BEST[$key]:-}" ]] || dpkg --compare-versions "$pver" gt "${BEST_VER[$key]}"; then
        BEST[$key]="$d"; BEST_VER[$key]="$pver"; SEEN_NAMES[$pname]=1
    fi
done
DEBS=()
for d in "${BEST[@]}"; do DEBS+=("$d"); done
echo "📦 待入库 ${#DEBS[@]} 个包（已按 包名+架构 去重，只取最新版本）:"
for d in "${DEBS[@]}"; do basename "$d"; done
if [[ ${#R2_DEBS[@]} -gt 0 ]]; then
    echo "📦 ${#R2_DEBS[@]} 个大包 (>${R2_THRESHOLD_BYTES} 字节) 将走 R2，不进入 aptly 仓库:"
    for k in "${!R2_DEBS[@]}"; do echo "   - $k → ${R2_DEBS[$k]}"; done
fi
# 导出供 rewrite-packages.sh 使用
{
    echo "# Auto-generated by publish.sh: R2-only packages (key=pkg/arch, value=path)"
    for k in "${!R2_DEBS[@]}"; do
        printf '%s\t%s\n' "$k" "${R2_DEBS[$k]}"
    done
} > "$ROOT/r2-debs.txt"

# --- 创建/复用 aptly 仓库（组件 main） ---
if ! apt repo show freelamp >/dev/null 2>&1; then
    apt repo create -distribution=bookworm -component=main freelamp >/dev/null
fi

# --- 入库 ---
# 说明：aptly 以 包名+版本+架构 作为主键。同包名的新版本（如 5.36.1+LL）发布时，
# 必须把该包名的旧版本全部移除，否则旧版本仍会残留在仓库/索引里。
# 因此入库前先把每个包名对应仓库里的所有版本都移除，再添加新文件。
for d in "${DEBS[@]}"; do
  meta="$(dpkg-deb -f "$d" Package)"
  pname="$(echo "$meta" | sed -n 's/^Package: //p')"
  [[ -z "$pname" ]] && { echo "⚠️ 跳过无法解析的包: $d"; continue; }
  if apt repo search freelamp "$pname" 2>/dev/null | grep -q .; then
    if apt repo remove freelamp "$pname" 2>/dev/null; then
      echo "♻️  已移除 $pname 的所有旧版本"
    fi
  fi
done
apt repo add freelamp "${DEBS[@]}"

# --- 打快照 ---
SNAP="freelamp-$(date +%Y%m%d%H%M%S)"
echo "📸 快照: $SNAP"
apt snapshot create "$SNAP" from repo freelamp

# --- 发布/更新到每个发行版 ---
while read -r distro; do
    [[ -z "$distro" || "$distro" == \#* ]] && continue
    if apt publish show "$distro" >/dev/null 2>&1; then
        echo "🔄 更新发行版 $distro ..."
        apt publish switch -gpg-key="$KEYID" "$distro" "$SNAP"
    else
        echo "🚀 首次发布 $distro ..."
        apt publish snapshot -gpg-key="$KEYID" -distribution="$distro" -component=main "$SNAP"
    fi
done < conf/distros.txt

# --- 写入 CNAME（自定义域名）与公钥，方便直接部署 ---
mkdir -p .aptly/public
cp CNAME .aptly/public/CNAME
cp keys/apt.key .aptly/public/apt.key

# --- 自动生成 index.html / dists/index.html / pool/index.html ---
bash scripts/generate-index.sh

# --- 生成 extrepo 数据源（index.yaml + 签名），随 GitHub Pages 一起发布 ---
bash scripts/generate-extrepo-data.sh

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 发布完成，产物在 .aptly/public/"
echo "   本地预览:  cd .aptly/public && python3 -m http.server 8080"
echo "   部署到 GitHub Pages: bash scripts/deploy-ghpages.sh"
apt publish list

# --- 把大包的 Filename: 改指向 R2 ---
# 此时 .aptly/public/ 已生成好（含 pool/ 下的所有 .deb）。
# 这一步:
#   1) 从 pool/ 删除大文件
#   2) 改 Packages/Packages.gz 里的 Filename: 字段
#   3) 重新签名 Release/InRelease
bash scripts/rewrite-packages.sh


# 注意：incoming/*.deb 绝不能清理！它是本源的全量数据库——
# aptly 状态不持久化，每次发布都用 incoming 里的全部 .deb 重建整个仓库。
# （历史教训：2026-08-25 清理导致线上仓库缩水到 3 个包）
# 旧版本由上面的"按包名 remove 再 add 最新版"机制自然淘汰。
